### ISSUE TITLE
Move console information out from getting started into its own topic.

### ISSUE THREAD

**Issue by ddebrunner** [quarks-edge/quarks.documentation#2]
I found the sudden addition of the console information in getting started somewhat jarring.

Getting started should be simple and end with links of what to do next.

Seems having the console introduction be its own page would be better.

**Comment by ddebrunner** [comment]
@home4slc Seems like a console page would be improved with images of the console.

**Comment by home4slc** [comment]
@ddebrunner +1

**Comment by home4slc** [comment]
Proposal for Quarks Documentation page wrt separating out the console information:

http://quarks-edge.github.io/quarks.documentation/index.html

Currently the Table of Content (should be Contents) has this:

Quarks
    ◦ Overview
    ◦ 
    ◦ Getting Started
    ◦ 
    ◦ Common Quarks Operations
    ◦ 
    ◦ Sample Programs
    ◦ 
    ◦ FAQ
    ◦ 
    ◦ Get Involved
    ◦ 
    ◦ Committers
Clicking on ‘Quarks’ brings you to a page that has the same Table of Contents, which seems a bit odd.
Could we remove the top level ‘Quarks’ link?

Regardless, if we want to add a console page, how about this for the order of the table:

```
◦ Overview
◦ 
◦ Getting Started
◦ 
◦ Common Quarks Operations
◦ 
◦ Sample Programs

Console
◦ 
◦ FAQ
◦ 
◦ Get Involved

◦ Committers
```

And then remove the content about the console from the getting started page.

For the layout of the Console page, here is a suggestion for main sections:
1. The Quarks application console - What is it?
   This could have the same content as the current content under ‘Accessing the Quarks application console’ section, since that section doesn’t talk about how to access it, it just describes it.
2.  A simple sample application that embeds the console 
   Add a sample to the scripts directory that contains a simple topology that embeds the console in the application.   Provide instructions on how to run it and then provide screen shots of a browser window of the console and point out the various features of the console.
3. Using the sample application as a guide, show the pertinent code / calls to embed the console in your own application.
   This means reformatting the current section called ‘Adding the console to your application’
4. Accessing the console
   This section is mostly unchanged except for fixing some of the things mentioned in other issues

I will write the simple sample console application.

**Comment by juliabamford** [comment]
@home4slc why don't we sync up to work on an update. I've cloned the project to my local system and started to remove the console content from the getting started page. I'd like to make sure that we're on the same page about the changes before I deliver them.

**Comment by home4slc** [comment]
How about you move the existing content to a new page, and then tell me what you are thinking for the new page.  If you have better ideas for the structure than what I have suggested, fire away!

**Comment by wmarshall484** [comment]
+1 for adding console to the top-level table of contents as it's a significant feature, although in general we should try to avoid adding too many things to the top-level TOC.
